DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS widgets CASCADE;

DROP TABLE IF EXISTS clients CASCADE;

DROP TABLE IF EXISTS dishes CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS dish_orders CASCADE;

DROP TABLE IF EXISTS feedbacks CASCADE;

CREATE TABLE dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  category VARCHAR(255) NOT NULL,
  photo_url VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  preparation INTEGER NOT NULL,
  description TEXT
);

CREATE TABLE clients (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone INTEGER NOT NULL,
  street VARCHAR NOT NULL,
  city VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  post_code VARCHAR(255) NOT NULL,
  favorite INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  email VARCHAR(255)
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  total INTEGER NOT NULL,
  estimate INTEGER NOT NULL,
  TIME TIMESTAMP NOT NULL,
  note TEXT
);

CREATE TABLE dish_orders (
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  cost INTEGER NOT NULL,
  dish_quantity SMALLINT NOT NULL
);

CREATE TABLE feedbacks (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL DEFAULT 5,
  content TEXT
);
